### PR TITLE
`Rust`: Init project

### PR DESCRIPTION
**Pull request by RyanPaulGannon**
# Contributor checklist

[x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
# Description

- Added files to setup project. Using [`iced`](https://iced.rs) GUI library for this, it has a nice (and I believe, easy to follow) structure. Sharing data between threads has also proved easier to achieve than when I tested with GTK
- Tested as working on Windows 11 emulator
- Currently crashes on Mac due to the `listen` function not running on the main thread. See this [module](https://github.com/Narsil/rdev?tab=readme-ov-file#os-caveats) for further details
- Requires testing on Linux, (I can and will probably test on something like ParrotOS through an emulator soon)

# Related issue

* #1  
* #9

### CODE REVIEW

**Comment by andrewtavis** [comment]
Exciting stuff @RyanPaulGannon! Really great 😊 I'll send commits here with the changes to the docs to add in the needed Rust shields, etc :)

**Comment by RyanPaulGannon** [comment]
Brilliant, nice one! If you need me to add anything to take some of the work off you I'm more than happy to do so 😄

I was thinking of creating the issues regarding testing in Linux and fixing the problem with macOS, but I wasn't sure whether the issues would be for when we have merged? What do you think? 😄

**Comment by andrewtavis** [comment]
Let's get it working for Linux and Mac and then we can merge 😊 Let me know if you have other ideas on how we could get it working for Mac!

**Comment by wkyoshida** [comment]
So excited for this! :star_struck::partying_face: 
Will take a look on the Linux side as well and report back!

---

Also, real quick - @RyanPaulGannon, iirc was there an error that popped up when testing on Mac? If so, would you mind adding a screenshot of it for reference? 

---

Thanks for the awesome update today!! Really great work!

**Comment by RyanPaulGannon** [comment]
Yeah, shoulda done that first! Et voila ..

`[1] 54401 trace trap  cargo run` is displayed upon a single key being tapped

Screenshot 2024-03-10 at 17 47 16

**Comment by RyanPaulGannon** [comment]
Okay, so the app loads on Ubuntu 22.04 using Parallels but there looks to be some kind of driver error. I got over the errors with the `x11` missing libraries through installing them. But as you can see from the screenshot that there is an error sending the event so I'm going to investigate this as well as the potential threading problem on macOS. 

Screenshot 2024-03-10 at 19 29 14

**Comment by andrewtavis** [comment]
All working on my end, @RyanPaulGannon! Let's do a slight bit of cleanup of the UI, and then we can bring this in. I think we can maybe remove the Translate button for now and we can add it back in later once we discuss whether what we have for the designs is the final (having buttons on click of the Scribe key via a modal).

**Comment by andrewtavis** [comment]
Let us know when the UI's where you want it to be, and then I'll be happy to merge!

**Comment by andrewtavis** [comment]
Let us know when this is ready for a final review, @RyanPaulGannon :) Thanks for all the work here!

**Comment by RyanPaulGannon** [comment]
@andrewtavis, let me know if there's anything else now before merging? I've spent some time trying to get to grips with the styling (the code needs splitting up, but for the moment, I've left it in `lib.rs` as its only one component). I have a few things in my head I'd like to create issues for to give others a chance to contribute should they wish - but if I end up working on them, I'm quite happy with that :)

**Comment by andrewtavis** [comment]
96be0d2 adds some general files that are normally in Scribe repos like a PR template, pre-commit hooks and a shell script to update Scribe-i18n once we start working with the localizations 😊 I also added setup directions to the readme and contribution guide :)

Thanks so much for the hard work here, @RyanPaulGannon! Great that we have Scribe-Desktop and Scribe-Android in the words at this point! 🚀

**Review by andrewtavis — APPROVED** [review]

**Pull request merged**
